version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ACCESS_TOKEN_USR=${GITHUB_USER}
        - ACCESS_TOKEN_PWD=${GITHUB_TOKEN}
        - BUILD_ARGS=${BUILD_ARGS}
    ports:
      - "9090:3000"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: 